version: '3'
services:

  point-rotation-0:
    build: .
    container_name: cw-point-rot-nup-0
    image: cw-point-rot-nup
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MQTT_CLIENT_ID=platfrom-dev-local
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC_IN_RADAR_SWEEP=CROWSNEST/SEAHORSE/RADAR/0/SWEEP
      - MQTT_TOPIC_IN_LIDAR_SWEEP=CROWSNEST/SEAHORSE/LIDAR/0/POINTCLOUD
      - MQTT_TOPIC_IN_HEADING=CROWSNEST/SEAHORSE/GNSS/0/JSON
      - MQTT_TOPIC_OUT_RADAR_NORTHUP=CROWSNEST/SEAHORSE/RADAR/0/NUP
      - MQTT_TOPIC_OUT_LIDAR_NORTHUP=CROWSNEST/SEAHORSE/LIDAR/0/NUP
      - CORR_HEADING=-10

  point-rotation-1:
    depends_on:
      - point-rotation-0
    image: cw-point-rot-nup
    container_name: cw-point-rot-nup-1
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MQTT_CLIENT_ID=platfrom-dev-local
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC_IN_RADAR_SWEEP=CROWSNEST/SEAHORSE/RADAR/1/SWEEP
      - MQTT_TOPIC_IN_LIDAR_SWEEP=CROWSNEST/SEAHORSE/LIDAR/1/POINTCLOUD
      - MQTT_TOPIC_IN_HEADING=CROWSNEST/SEAHORSE/GNSS/0/JSON
      - MQTT_TOPIC_OUT_RADAR_NORTHUP=CROWSNEST/SEAHORSE/RADAR/1/NUP
      - MQTT_TOPIC_OUT_LIDAR_NORTHUP=CROWSNEST/SEAHORSE/LIDAR/1/NUP
      - CORR_HEADING=-10